const AllIDs = {
  ic_test: {
    NFT_ALONE_FACTORY_ID: '7fnwe-5qaaa-aaaai-qa2ka-cai',
    NFT_MULTI_FACTORY_ID: '7cmqq-qiaaa-aaaai-qa2kq-cai',
    WICP_MOTOKO_ID: '7xlb5-raaaa-aaaai-qa2ja-cai',
    STORAGE_EMAIL_CID: 'weq3k-2aaaa-aaaai-qaitq-cai',
    WICP_STORAGE_ID: '6bazw-eqaaa-aaaai-qa2ma-cai',
    NFT_MULTI_STORAGE_ID: 'yv2ms-ryaaa-aaaai-qa5ea-cai',
    NFT_ALONE_STORAGE_ID: '4py4s-laaaa-aaaai-qblra-cai',
    NFT_ZOMBIE_FACOTRY_ID: '46emz-giaaa-aaaah-qcg4q-cai',
    NFT_ZOMBIE_STORAGE_ID: '4xhhf-qaaaa-aaaah-qcg5a-cai',
    NFT_THEME_FACTORY_ID: 'wprbd-cyaaa-aaaai-qbb3a-cai',
    NFT_THEME_STORAGE_ID: 'wiqhx-paaaa-aaaai-qbb3q-cai',
    NFT_1155_FACTORY_ID: 'ktzvt-ayaaa-aaaai-qbeeq-cai',
    NFT_1155_STORAGE_ID: 'k226p-wqaaa-aaaai-qbefa-cai',
    PROFILE_FACTORY_ID: 'yolq2-kaaaa-aaaai-qbhga-cai',
    NFT_THEME_1155_FACTORY_ID: 'ch44z-kiaaa-aaaai-qfklq-cai',
    NFT_THEME_1155_STORAGE_ID: 'dksyx-faaaa-aaaai-qfkma-cai',
    NFT_CREATE_FACTORY_ID: 'vqvbt-iqaaa-aaaai-qmika-cai',
    FAVORITE_STORAGE_ID: 'lwdjq-taaaa-aaaai-qni7q-cai',
    LEDGER_CANISTER_ID: 'ryjl3-tyaaa-aaaaa-aaaba-cai',

    STAKE_NFT_ID: 'umlgv-5yaaa-aaaai-qk6xa-cai',
    II_LOCAL_URL: 'https://identity.ic0.app/#authorize',
    HOST_URL: 'https://boundary.ic0.app/',
  },
  dev: {
    NFT_ALONE_FACTORY_ID: 'q4eej-kyaaa-aaaaa-aaaha-cai',
    NFT_MULTI_FACTORY_ID: 'sgymv-uiaaa-aaaaa-aaaia-cai',
    WICP_MOTOKO_ID: 'qhbym-qaaaa-aaaaa-aaafq-cai',
    STORAGE_EMAIL_CID: 't6rzw-2iaaa-aaaaa-aaama-cai',
    ICD3D_MAIL_ID: 'hleti-rqaaa-aaaai-qll5a-cai',
    ICD3D_MAIL_STORAGE_ID: 'hmfv4-4iaaa-aaaai-qll5q-cai',
    WICP_STORAGE_ID: '2i5un-taaaa-aaaaa-aab7q-cai',
    NFT_MULTI_STORAGE_ID: 'n4t2m-tyaaa-aaaaa-aacba-cai',
    NFT_ALONE_STORAGE_ID: 'kuwf5-5qaaa-aaaaa-aacqq-cai',
    NFT_ZOMBIE_FACOTRY_ID: 'novnv-7iaaa-aaaaa-aacca-cai',
    NFT_ZOMBIE_STORAGE_ID: 'n3s4y-6aaaa-aaaaa-aacbq-cai',
    NFT_THEME_FACTORY_ID: 'mr56c-4qaaa-aaaaa-aacgq-cai',
    NFT_THEME_STORAGE_ID: 'mw4yw-riaaa-aaaaa-aacga-cai',
    NFT_1155_FACTORY_ID: 'ozhbh-oqaaa-aaaaa-aackq-cai',
    NFT_1155_STORAGE_ID: 'oqek3-yyaaa-aaaaa-aacla-cai',
    PROFILE_FACTORY_ID: 'pgpsq-niaaa-aaaaa-aacoa-cai',
    NFT_THEME_1155_FACTORY_ID: 'kbruq-4yaaa-aaaaa-aacta-cai',
    NFT_THEME_1155_STORAGE_ID: 'kis7m-kqaaa-aaaaa-aacsq-cai',

    NFT_CREATE_FACTORY_ID: '',

    STAKE_NFT_ID: 'umlgv-5yaaa-aaaai-qk6xa-cai',
    LEDGER_CANISTER_ID: 'ryjl3-tyaaa-aaaaa-aaaba-cai',
    II_LOCAL_URL: 'http://localhost:8888/',
    HOST_URL: 'http://localhost:8888/',
  },
};

export default AllIDs;
